export * from './account.service';
import { AccountService } from './account.service';
export * from './app.service';
import { AppService } from './app.service';
export * from './associatedQuestion.service';
import { AssociatedQuestionService } from './associatedQuestion.service';
export * from './booking.service';
import { BookingService } from './booking.service';
export * from './bookingAddOn.service';
import { BookingAddOnService } from './bookingAddOn.service';
export * from './cardActions.service';
import { CardActionsService } from './cardActions.service';
export * from './cardCollectionTemplate.service';
import { CardCollectionTemplateService } from './cardCollectionTemplate.service';
export * from './cardGroup.service';
import { CardGroupService } from './cardGroup.service';
export * from './cards.service';
import { CardsService } from './cards.service';
export * from './conversations.service';
import { ConversationsService } from './conversations.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './invContainerFacility.service';
import { InvContainerFacilityService } from './invContainerFacility.service';
export * from './invItemAvailability.service';
import { InvItemAvailabilityService } from './invItemAvailability.service';
export * from './invItemFacility.service';
import { InvItemFacilityService } from './invItemFacility.service';
export * from './invItemRateType.service';
import { InvItemRateTypeService } from './invItemRateType.service';
export * from './invItemType.service';
import { InvItemTypeService } from './invItemType.service';
export * from './inventoryContainer.service';
import { InventoryContainerService } from './inventoryContainer.service';
export * from './inventoryItem.service';
import { InventoryItemService } from './inventoryItem.service';
export * from './note.service';
import { NoteService } from './note.service';
export * from './partner.service';
import { PartnerService } from './partner.service';
export * from './partnerSetting.service';
import { PartnerSettingService } from './partnerSetting.service';
export * from './partnerSettingDefinitions.service';
import { PartnerSettingDefinitionsService } from './partnerSettingDefinitions.service';
export * from './partnerSettingGroup.service';
import { PartnerSettingGroupService } from './partnerSettingGroup.service';
export * from './profiles.service';
import { ProfilesService } from './profiles.service';
export * from './qnaMaker.service';
import { QnaMakerService } from './qnaMaker.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './trabbleBot.service';
import { TrabbleBotService } from './trabbleBot.service';
export * from './trabbleMessages.service';
import { TrabbleMessagesService } from './trabbleMessages.service';
export * from './unansweredQuestions.service';
import { UnansweredQuestionsService } from './unansweredQuestions.service';
export const APIS = [AccountService, AppService, AssociatedQuestionService, BookingService, BookingAddOnService, CardActionsService, CardCollectionTemplateService, CardGroupService, CardsService, ConversationsService, FilesService, InvContainerFacilityService, InvItemAvailabilityService, InvItemFacilityService, InvItemRateTypeService, InvItemTypeService, InventoryContainerService, InventoryItemService, NoteService, PartnerService, PartnerSettingService, PartnerSettingDefinitionsService, PartnerSettingGroupService, ProfilesService, QnaMakerService, TestService, TrabbleBotService, TrabbleMessagesService, UnansweredQuestionsService];
