/**
 * Trabble Backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InventoryItemRate } from './inventoryItemRate';


export interface InventoryItemAvailabilityDTO {
    availabilityStart?: string;
    availabilityEnd?: string;
    status?: InventoryItemAvailabilityDTO.StatusEnum;
    note?: string;
    itemId?: string;
    quantity?: number;
    bookedQuantity?: number;
    rates?: Array<InventoryItemRate>;
    id?: string;
    createdTime?: Date;
    updatedTime?: Date;
}
export namespace InventoryItemAvailabilityDTO {
    export type StatusEnum = 'Available' | 'Booked' | 'Closed';
    export const StatusEnum = {
        Available: 'Available' as StatusEnum,
        Booked: 'Booked' as StatusEnum,
        Closed: 'Closed' as StatusEnum
    }
}
